services:
  cvbuilder:
    build: .
    container_name: cvbuilder_app
    ports:
      - "5000:5000"
    volumes:
      - ${DATA_DIR:-./data}:/app/data:/app/data   # Mount des Data-Verzeichnisses
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
